name: mikan_flutter
description: mikanani.me

version: 1.0.0-RC25+47

publish_to: none

environment:
  sdk: ">=2.14.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.10.2
  firebase_analytics: ^8.3.4
  firebase_crashlytics: ^2.4.0
  path_provider: ^2.0.7
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  dio_http2_adapter: ^2.0.0
  html: ^0.15.0
  provider: ^6.0.1
  oktoast: ^3.1.5
  pull_to_refresh: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  palette_generator: ^0.3.2
  flutter_spinkit: ^5.1.0
  fluentui_system_icons: ^1.1.152
  clipboard: ^0.1.3
  url_launcher: ^6.0.17
  share_plus: ^3.0.4
  flutter_widget_from_html: ^0.8.2
  extended_sliver: ^2.0.1
  extended_image: ^5.1.3
  waterfall_flow: ^3.0.1
  modal_bottom_sheet: ^2.0.0
  jiffy: ^4.1.0
  android_intent_plus: ^3.0.2
  isolate: ^2.1.1
  connectivity_plus: ^2.1.0
  ff_annotation_route_core: ^2.0.3
  ff_annotation_route_library: ^2.0.4
  sprung: ^3.0.0
  sliver_tools: ^0.2.5
  bitsdojo_window: ^0.1.1+1
  flutter_displaymode: ^0.3.2
  infinite_carousel: ^1.0.1
  flex_color_picker: ^2.2.0
  flutter_lints: ^1.0.4

dev_dependencies:
  build_runner: ^2.1.5
  json_serializable: ^6.1.1
  hive_generator: ^1.1.1
  flutter_launcher_icons: ^0.9.2
  yaml: ^3.1.0
#  derry: ^1.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/mikan.png"


## pub global activate derry
## derry upgrade
#scripts:
#  # derry build
#  build:
#    - flutter pub run build_runner build --delete-conflicting-outputs
#  # derry watch_build
#  watch_build:
#    - flutter pub run build_runner watch --delete-conflicting-outputs
#  # derry ff_route_first
#  ff_route_first:
#    - flutter pub global activate ff_annotation_route
#    - ff_route -s --route-constants --route-helper --route-names --no-is-initial-route --supper-arguments
#  # derry ff_route
#  ff_route: ff_route


