name: daily build
on:
  push:
    tags:
      - v*
jobs:
  build:
    name: release build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup jdk
        uses: actions/setup-java@v1
        with:
          java-version: '8.x'
        run: java -version
      - name: setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: build apk
        run: |
          flutter pub get
          flutter build apk
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
      - name: sign build apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      - name: build windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows
          Compress-Archive -Path build/windows/runner/Release/* windows-release.zip
      - name: release build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release-apk/*release-signed.apk,build/windows/runner/windows-release.zip"
          token: ${{ secrets.ACTION_TOKEN }}
