name: build aab
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
    name: Release build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build aab
        run: |
          \cp -f pubspec.yaml assets
          flutter pub get
          flutter build -v appbundle --release
          ls build/app/outputs/bundle/release
      - name: Sign build aab
        uses: iota9star/sign-android-release@v1.0.5
        with:
          releaseDirectory: build/app/outputs/bundle/release
          fileRegex: .*-release.aab
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.3"
      - name: Release to github
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "build/app/outputs/bundle/release/*-release-signed.aab"
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ github.event.inputs.TAG }}
      - name: Release to GP
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: io.nichijou.flutter.mikan
          releaseFiles: 'build/app/outputs/bundle/release/*-release-signed.aab'
          track: production
          inAppUpdatePriority: 5
          userFraction: 1.0
          mappingFile: build/app/outputs/mapping/release/mapping.txt
