name: build windows
on:
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Set a Tag'
        required: true
        default: ''
  push:
    tags:
      - v*
jobs:
  build:
    name: Release build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Build windows
        run: |
          Copy-Item -Path pubspec.yaml -Destination assets -Force
          flutter config --enable-windows-desktop
          flutter build windows --release
          dir build/windows/runner/Release
          Compress-Archive -Path build/windows/runner/Release/* releases/windows-win32-release.zip -Force
      - name: Release build
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "releases/*-release.zip"
          token: ${{ secrets.ACTION_TOKEN }}
          tag: ${{ github.event.inputs.TAG }}
      - name: Write meta file
        run: |
          dart scripts/releases.dart
      - name: Commit binary files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-u'
          push_options: '--force'
          commit_message: ":bookmark: Release binary files."
          file_pattern: releases/*-release.zip releases/meta.json
